vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO sogou/workflow
    REF v0.9.2
    SHA512 08a130b6fdb93744dec7a46d4c1144a084d61bc73b5367cf41f0863e10b8c0f4d2a7ac12425c5c460852b06ca3262ce00d6094144635881da3ed691c746dc98f
    HEAD_REF master
)

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
)

vcpkg_install_cmake()

include(CMakePackageConfigHelpers)

set(PROJECT_NAME ${PORT})
set(CONFIG_INC_DIR include)
set(CONFIG_LIB_DIR lib)
set(CONFIG_SHARE_DIR share)
set(SHARE_DIRECTORY ${CONFIG_SHARE_DIR}/${PROJECT_NAME})
file(MAKE_DIRECTORY ${SHARE_DIRECTORY})

configure_package_config_file(
	${SOURCE_PATH}/${PROJECT_NAME}-config.cmake.in
	${CURRENT_PACKAGES_DIR}/${SHARE_DIRECTORY}/${PROJECT_NAME}-config.cmake
	INSTALL_DESTINATION ${CURRENT_PACKAGES_DIR}
	PATH_VARS CONFIG_INC_DIR CONFIG_LIB_DIR
)

file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/${CONFIG_INC_DIR})
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/${CONFIG_LIB_DIR}/cmake)
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/${CONFIG_SHARE_DIR})
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/${CONFIG_LIB_DIR}/cmake)

file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/${CONFIG_SHARE_DIR}/${PROJECT_NAME} RENAME copyright)

message("Installing done")