vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO sogou/workflow
    REF v0.9.1
    SHA512 db0294b2c021b67cbee9a5387d585598445e13ce8d3986ffd71109fe3a8893301202e99e5b0cf2807dff8c57b5ca63c6f74ed08d06279dd49d45e49dca8a8557
    HEAD_REF master
)

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
)

vcpkg_install_cmake()

include(CMakePackageConfigHelpers)

set(PROJECT_NAME ${PORT})
set(CONFIG_INC_DIR include)
set(CONFIG_LIB_DIR lib)
set(CONFIG_SHARE_DIR share)
set(SHARE_DIRECTORY ${CONFIG_SHARE_DIR}/${PROJECT_NAME})
file(MAKE_DIRECTORY ${SHARE_DIRECTORY})

configure_package_config_file(
	${SOURCE_PATH}/${PROJECT_NAME}-config.cmake.in
	${CURRENT_PACKAGES_DIR}/${SHARE_DIRECTORY}/${PROJECT_NAME}-config.cmake
	INSTALL_DESTINATION ${CURRENT_PACKAGES_DIR}
	PATH_VARS CONFIG_INC_DIR CONFIG_LIB_DIR
)

file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/${CONFIG_INC_DIR})
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/${CONFIG_LIB_DIR}/cmake)
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/${CONFIG_SHARE_DIR})
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/${CONFIG_LIB_DIR}/cmake)

file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/${CONFIG_SHARE_DIR}/${PROJECT_NAME} RENAME copyright)

message("Installing done")